name: Test arlas_cli

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Start the stack
      run: scripts/start_stack.sh
    - name: Run indices/collections tests
      run: pytest ./tests/test_arlas_cli.py -v
    - name: Run iam tests
      run: pytest ./tests/test_iam_orgs_users.py -v
    - name: Stop the stack
      run: scripts/stop_stack.sh
